name: testLoadSRPBill

on:
  workflow_dispatch:

jobs:
  run-secure-task:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create token.pickle from secret
      run: |
        echo "$TOKEN_PICKLE_BASE64" | base64 --decode > token.pickle
      env:
        TOKEN_PICKLE_BASE64: ${{ secrets.TOKEN_PICKLE_BASE64 }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r bills_auto_requirements.txt  # Install dependencies from requirements.txt
        # Install Selenium
        pip install selenium
        pip install selenium_stealth
        
        # Update package lists and install necessary tools
        sudo apt-get update
        sudo apt-get install -y unzip xvfb
        
        # Download the specified ChromeDriver version
        wget -q "https://storage.googleapis.com/chrome-for-testing-public/130.0.6723.69/linux64/chromedriver-linux64.zip"
        
        # Unzip and move ChromeDriver to /usr/local/bin/
        sudo unzip chromedriver-linux64.zip
        sudo mv -f chromedriver-linux64/chromedriver /usr/local/bin/
        rm chromedriver-linux64.zip
        
        # Make ChromeDriver executable
        sudo chmod +x /usr/local/bin/chromedriver
        
        # Install Google Chrome (latest by default, or specify version)
        sudo apt-get install libxss1 libayatana-appindicator1 libindicator7
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome*.deb

    - name: Set up display for headless Chrome
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x16 &

    - name: Run Python script with secrets
      env:
        SPLITWISE_API_KEY: ${{ secrets.SPLITWISE_API_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        SRP_USERNAME: ${{ secrets.SRP_USERNAME }}
        SRP_PWD: ${{ secrets.SRP_PWD }}
        JOB: "Electricity Bill"
        TENANT_ID: "29057780"

      run: |
        # Ensure Python is installed and available
        python3 --version
        # Run your script (that utilizes Selenium)
        python3 src/load_bill.py
